name: Apptainer Build Deploy

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    name: Build and Deploy 'Tainer
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Install Apptainer
        uses: uw-psych/apptainer-actions/setup@main
      
      - name: Check out
        uses: actions/checkout@v4

      - name: Set tag
        shell: bash
        run: |
          export IMAGE_VERSION=${GITHUB_REF_NAME#v}
          echo "IMAGE_VERSION=${IMAGE_VERSION}" >> "${GITHUB_ENV}"

      - name: Build and push image
        uses: uw-psych/apptainer-actions/build-and-push@main
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
        with:
          deffile: image.def
          image-version: ${{ env.IMAGE_VERSION }}
          image-url: "oras://ghcr.io/g5t/stacktainer/splitrun:${{ env.IMAGE_VERSION }}"
          add-tags: "latest"
          
